server:
  port: 8088

spring:
  application:
    name: gitlab-merge
  redis:
    database: 19
    port: 6379
    host: r-uf65yfcoxr4hmppfi1.redis.rds.aliyuncs.com
    password: '#JiojklAd33b3f211e276#@d76'

logging:
  level:
    root: INFO
    com.example.gitlabmerge: INFO


