server:
  port: 8088

spring:
  application:
    name: gitlab-merge
  redis:
    database: 19
    port: 6379
    host: xxxx
    password: xxx

logging:
  level:
    root: INFO
    com.example.gitlabmerge: INFO


